services:
  docker-cronjob-be:
    depends_on:
      - db
    build:
      context: .
    container_name: cronjob-be
    hostname: cronjob-be
    ports:
      - 8080:8080
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: cronjob
      POSTGRES_PASSWORD: cronjob
      POSTGRES_DB: cronjob
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  pgdata:
